FROM ubuntu

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update
RUN apt install -y python3-dev python3-pip  python3-opencv vim-tiny vim libopencv-dev
RUN pip3 install Cython
RUN pip3 install numpy
RUN apt install -y mosquitto-clients
RUN apt install -y mosquitto
RUN pip3 install paho-mqtt
