FROM w251/l4t-ml:r32.4.4-py3

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update
RUN apt install -y python3-dev python3-pip  python3-opencv vim-tiny vim libopencv-dev
RUN pip3 install Cython
RUN pip3 install numpy
RUN apt install -y mosquitto-clients
RUN apt install -y mosquitto
RUN pip3 install paho-mqtt 

RUN pip3 install facenet-pytorch

RUN git clone https://github.com/timesler/facenet-pytorch.git facenet_pytorch

